name: Keep ML API Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # every 10 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend
        run: curl -s https://fullstackcreditcardfraudulenttransaction.onrender.com/health